import './globals.css';
import './styles/style.css';
import { Open_Sans } from 'next/font/google'
import Navbar from './components/Navbar'
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import { AuthProvider } from './Providers';

const OpenSans = Open_Sans({ subsets: ['latin'] })

export const metadata = {
  title: 'Next Auth',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="it">
      <body className={OpenSans.className}>
      <AuthProvider>
       <Navbar />
       <ToastContainer position="top-center" autoClose={3000} />
       {children}
       </AuthProvider>
      </body>
    </html>
  )
}
